//
//  DataManager.swift
//  BithumbHomeworkJskang
//
//  Created by 강진석 on 2021/03/03.
//

import Foundation

class DataManager {
    static let shared = DataManager()
    private init() {}
    
    // 코인원 API Response에 코인 한글명 존재하지 않으므로 앱에서 데이터 생성
    func getCurrencyKoreanName(currency:String) -> String {
        return self.currencyToKoreanNameDic[currency.uppercased()] ?? ""
    }
    
    private let currencyToKoreanNameDic =
        ["1INCH":"1인치",
         "AAVE":"에이브",
         "ABL":"에어블록",
         "AIP":"에이아이피",
         "ALPHA":"알파 파이낸스 랩",
         "AMO":"아모코인",
         "ANKR":"앵커 네트워크",
         "AOA":"오로라",
         "ARPA":"알파체인",
         "ASM":"어셈블 프로토콜",
         "ASTA":"아스타",
         "AVAX":"아발란체",
         "AXL":"엑시얼",
         "AXS":"엑시 인피니티",
         "BAAS":"바스아이디",
         "BAL":"발란서",
         "BAND":"밴드 프로토콜",
         "BASIC":"베이직",
         "BAT":"베이직어텐션토큰",
         "BCHA":"비트코인 캐시 에이비씨",
         "BEL":"벨라 프로토콜",
         "BFC":"비에프코인",
         "BMP":"비엠피",
         "BNA":"바나나톡",
         "BNT":"방코르",
         "BORA":"보라",
         "BOT":"바운스 토큰",
         "BTG":"비트코인 골드",
         "BTT":"비트토렌트",
         "BZRX":"비지엑스 프로토콜",
         "CAD":"캔디 프로토콜",
         "CAMP":"캠프코인",
         "CBANK":"크립토뱅크",
         "CBK":"코박 토큰",
         "CELEB":"셀럽 플러스",
         "CKB":"너보스",
         "CLB":"클라우드브릭",
         "COMP":"컴파운드",
         "COS":"콘텐토스",
         "CRV":"커브",
         "CTSI":"카르테시",
         "DAD":"다드",
         "DATA":"스트리머",
         "DIA":"디아",
         "DMG":"디엠엠 거버넌스",
         "DODO":"도도",
         "DON":"도니 파이낸스",
         "DRC":"디알씨 모빌리티",
         "DRM":"두드림체인",
         "DUCATO":"두카토",
         "DVI":"디비전",
         "DVX":"데리백스",
         "EGG":"네스트리",
         "EXE":"8X8 프로토콜",
         "FCR":"프롬카",
         "FET":"페치",
         "FLETA":"플레타",
         "FRONT":"프론티어",
         "FTT":"에프티엑스 토큰",
         "GAS":"가스",
         "GET":"겟 프로토콜",
         "GOM2":"고머니2",
         "GRT":"더그래프",
         "HANDY":"핸디",
         "HARD":"하드 프로토콜",
         "HIBS":"하이블럭스",
         "HINT":"힌트체인",
         "HUM":"휴면스케이프",
         "IBP":"아이비피 토큰",
         "INJ":"인젝티브 프로토콜",
         "IOTX":"아이오텍스",
         "IPX":"타키온 프로토콜",
         "ISDT":"아이스타더스트",
         "ISR":"인슈리움",
         "JST":"저스트",
         "KAI":"카르디아체인",
         "KAVA":"카바",
         "KDAG":"킹디에이쥐",
         "KNC":"카이버",
         "KRT":"테라 KRT",
         "KSC":"케이스타라이브",
         "KSM":"쿠사마",
         "KSP":"클레이스왑",
         "KVI":"케이브이아이",
         "LBXC":"럭스 바이오",
         "LINA":"리니어 파이낸스",
         "LMCH":"라탐캐시",
         "LUA":"루아 토큰",
         "MAP":"맵 프로토콜",
         "MATIC":"폴리곤",
         "MBL":"무비블록",
         "MCH":"미콘캐시",
         "MIR":"미러 프로토콜",
         "MLK":"밀크",
         "MNR":"미네랄",
         "MOV":"모티브",
         "MSB":"미스블록",
         "MTA":"메타",
         "MTS":"메티스",
         "MVC":"마일벌스",
         "NEST":"네스트 프로토콜",
         "NFUP":"엔에프유피",
         "OBSR":"옵저버",
         "OGN":"오리진 프로토콜",
         "OMG":"오미세고 네트워크",
         "ONG":"온톨로지가스",
         "ONT":"온톨로지",
         "ONX":"오니엑스",
         "ORBS":"오브스",
         "ORC":"오르빗체인",
         "PCI":"페이코인",
         "PIB":"피블",
         "PICA":"피카",
         "POD":"포도",
         "PROM":"프로메테우스",
         "PSC":"폴스타코인",
         "PURE":"퓨리에버",
         "PXL":"픽셀",
         "QTBK":"퀀트북",
         "QTCON":"퀴즈톡",
         "REDI":"레디",
         "REN":"렌",
         "RNX":"루넥스",
         "RUSH":"러쉬 코인",
         "SHOW":"쇼고",
         "SIX":"식스",
         "SNX":"신세틱스 네트워크 토큰",
         "SOC":"소다코인",
         "SRM":"세럼",
         "STAKE":"스테이크",
         "STPL":"스트림 프로토콜",
         "STPT":"에스티피",
         "SUN":"썬",
         "SUSHI":"스시",
         "SXP":"스와이프",
         "TEMCO":"템코",
         "TEN":"테넷",
         "TIP":"팁",
         "TMC":"티엠씨",
         "TMTG":"더마이다스터치골드",
         "TOM":"톰 파이낸스",
         "TOMOE":"토모체인",
         "TOROCUS":"토로커스",
         "TRCL":"트리클",
         "TRIX":"트라이엄프엑스",
         "UMA":"우마",
         "UOS":"울트라",
         "VIVI":"비비",
         "VSYS":"브이시스템즈",
         "WIKEN":"위드",
         "XPN":"판테온X",
         "ZIL":"질리카",
         "ZRX":"제로엑스",
         "ADA":"에이다",
         "ATOM":"코스모스아톰",
         "BCH":"비트코인 캐시",
         "BSV":"비트코인사토시비전",
         "BTC":"비트코인",
         "DOT":"폴카닷",
         "EOS":"이오스",
         "ETC":"이더리움 클래식",
         "ETH":"이더리움",
         "IOTA":"아이오타",
         "KLAY":"클레이튼",
         "LINK":"체인링크",
         "LTC":"라이트코인",
         "LUNA":"루나",
         "NEO":"네오",
         "QTUM":"퀀텀",
         "SKLAY":"에스클레이",
         "TRX":"트론",
         "XLM":"스텔라루멘",
         "XRP":"리플",
         "XTZ":"테조스"
        ]
}
