//
//  CoinListRouter.swift
//  BithumbHomeworkJskang
//
//  Created by 강진석 on 2021/03/02.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CoinListRoutingLogic
{
    func routeToCoinDetail(coinData:CoinData)
}

protocol CoinListDataPassing
{
    var dataStore: CoinListDataStore? { get }
}

class CoinListRouter: NSObject, CoinListRoutingLogic, CoinListDataPassing
{
    
    
    weak var viewController: CoinListViewController?
    var dataStore: CoinListDataStore?
    
    // 코인 상세 화면으로 이동
    func routeToCoinDetail(coinData:CoinData) {
        let detailVC = CoinDetailViewController.init(nibName: "CoinDetailViewController", bundle:nil)
        detailVC.modalPresentationStyle = .fullScreen
        detailVC.coinData = coinData
        detailVC.delegate = self.viewController
        self.viewController?.present(detailVC, animated: true, completion: nil)
    }
}
