//
//  CoinListModels.swift
//  BithumbHomeworkJskang
//
//  Created by 강진석 on 2021/03/02.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum CoinList
{
    // 모든 코인목록 가져오기에 대한 모델
    enum AllCoinList
    {
        struct Request
        {
        }
        struct Response
        {
            var coinList:[CoinData]?
        }
        struct ViewModel
        {
            var coinList:[CoinData]?
        }
    }
    
    // 비트코인 가져오기에 대한 모델
    enum BTCCoin
    {
        struct Request
        {
        }
        struct Response
        {
            var btcCoin:CoinData?
        }
        struct ViewModel
        {
            var btcCoin:CoinData?
        }
    }
    
    // UI 조건에 따른 목록 재구성 기능에 대한 모델
    enum CoinListByInfo
    {
        struct Request
        {
            var coinList:[CoinData]
            var query:String?
            var tapIndex:Int
            var sortIndex:Int
            var state:SortState
            
            init(coinList:[CoinData],
                 query:String?,
                 tapIndex:Int,
                 sortIndex:Int,
                 state:SortState) {
                
                self.coinList = coinList
                self.query = query
                self.tapIndex = tapIndex
                self.sortIndex = sortIndex
                self.state = state
            }
        }
        struct Response
        {
            var coinList:[CoinData]
        }
        struct ViewModel
        {
            var coinList:[CoinData]
        }
    }
}
