//
//  CoinListPresenter.swift
//  BithumbHomeworkJskang
//
//  Created by 강진석 on 2021/03/02.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CoinListPresentationLogic
{
    func presentAllCoinList(response: CoinList.AllCoinList.Response)
    func presentBTCCoin(response: CoinList.BTCCoin.Response)
    func presentCoinListByInfo(response: CoinList.CoinListByInfo.Response)
}

class CoinListPresenter: CoinListPresentationLogic
{
    
    weak var viewController: CoinListDisplayLogic?
    
    func presentAllCoinList(response: CoinList.AllCoinList.Response) {
        var viewModel = CoinList.AllCoinList.ViewModel()
        viewModel.coinList = response.coinList
        viewController?.displayAllCoinList(viewModel: viewModel)
    }
    
    func presentBTCCoin(response: CoinList.BTCCoin.Response) {
        var viewModel = CoinList.BTCCoin.ViewModel()
        viewModel.btcCoin = response.btcCoin
        viewController?.displayBTCCoin(viewModel: viewModel)
    }
    
    func presentCoinListByInfo(response: CoinList.CoinListByInfo.Response) {
        let viewModel = CoinList.CoinListByInfo.ViewModel(coinList: response.coinList)
        viewController?.displayCoinListByInfo(viewModel: viewModel)
    }
}
